# Generated by Django 5.0.1 on 2024-01-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_app', '0002_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
